In [10]:
import numpy  as np

1. Array  VS  List

In [4]:
lst=[1,2,3]
print(lst)
print(type(lst))
print("------")
arr= np.array([1,3,2])
print(arr)
print(type(arr))
print("--------")

print(arr == lst)
print(arr.tolist() == lst)
print(sorted(arr) == sorted(lst))



[1, 2, 3]
<class 'list'>
------
[1 3 2]
<class 'numpy.ndarray'>
--------
[ True False False]
False
True


2. Adding elements in an Arrays VS List

In [15]:
lst=[1,2,3]
arr= np.array([1,3,2])
print(lst)
lst.append(4)
print(lst)
print('------------')

print(arr)
arr = np.append(arr,4)
print(arr)


[1, 2, 3]
[1, 2, 3, 4]
------------
[1 3 2]
[1 3 2 4]


3. Removing elements in an Arrays VS List

In [20]:
lst=[1,2,3]
arr= np.array([1,3,2])
print(lst)
del lst[-1]
print(lst)
print("-----------")
print(arr)
arr=np.delete(arr,-1)
print(arr)

[1, 2, 3]
[1, 2]
-----------
[1 3 2]
[1 3]




4.Updating elements in an Arrays VS List

In [24]:
lst=[1,2,3]
print(lst)
lst[-1]=5
lst[-2]=4
print(lst)
print("---------")
arr= np.array([1,3,2])
print(arr)
arr[-1]=9
arr[-2]=7
print(arr)



[1, 2, 3]
[1, 4, 5]
---------
[1 3 2]
[1 7 9]


5. Array VS List Comparison

In [27]:
import time
#Creating the data
my_list = list(range(10000000))
my_array = np.arange(10000000)

#search time for list
start_time = time.time()
for _ in range(100):
    if 5000000 in my_list:
        pass
end_time = time.time()
print("List:", end_time - start_time)

#search time for array
start_time = time.time()
for _ in range(100):
    if 5000000 in my_array:
        pass
end_time = time.time()
print("Array:", end_time - start_time)

List: 5.70456337928772
Array: 0.6158919334411621
